
mkdir -p CMPN/SE/A
mkdir -p CMPN/SE/B
mkdir -p CMPN/SE/C
mkdir -p CMPN/TE/A
mkdir -p CMPN/TE/B
mkdir -p CMPN/TE/C
mkdir -p CMPN/BE/A
mkdir -p CMPN/BE/B
mkdir -p CMPN/BE/C
mkdir -p ETRX/SE/A
mkdir -p ETRX/SE/B
mkdir -p ETRX/TE/A
mkdir -p ETRX/TE/B
mkdir -p ETRX/BE/A
mkdir -p ETRX/BE/B
mkdir -p CMPN/SE/A
mkdir -p CMPN/SE/B
mkdir -p CMPN/SE/C
mkdir -p CMPN/TE/A
mkdir -p CMPN/TE/B
mkdir -p CMPN/TE/C
mkdir -p CMPN/BE/A
mkdir -p CMPN/BE/B
mkdir -p EXTC/BE/C
mkdir -p IT/SE/A
mkdir -p IT/SE/B
mkdir -p IT/TE/A
mkdir -p IT/TE/B
mkdir -p IT/BE/A
mkdir -p IT/BE/B
mkdir -p INST/SE/A
mkdir -p INST/SE/B
mkdir -p INST/TE/A
mkdir -p INST/TE/B
mkdir -p INST/BE/A
mkdir -p INST/BE/B

